# Generated by Django 3.2.23 on 2023-11-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biashara', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='white', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='kenya', max_length=50),
        ),
    ]
